# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "daily"
      # Include a list of updated dependencies
      # with a prefix determined by the dependency group
      commit-message:
        prefix: ":robot:"
        include: "scope"
      labels:
        - "python"
        - "dependencies"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":robot:"
      include: "scope"
    labels:
      - "actions"
      - "dependencies"
