# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "python"
      - "dependencies"
    # Include a list of updated dependencies
    commit-message:
      prefix: ":robot:"
      include: "scope"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "actions"
      - "dependencies"
    commit-message:
      prefix: ":robot:"
      include: "scope"