site_name: Ublox-API
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: img/index.png
  favicon: img/satellite.png
repo_name: acutaia/goeasy-ublox_api
repo_url: https://github.com/acutaia/goeasy-ublox_api

nav:
  - GoEasy: index.md
  - Ublox Service:
      - ublox_reference_service_platform/overview.md
      - ublox_reference_service_platform/ublox_api.md
  - Deployment: deployment.md