name: Test
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
          # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install wheel
          pip install poetry
          poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Lint with flake8
        run: |
          flake8 app/
      - name: Check Black format
        run: |
          black app tests --check
      - name: Test with pytest
        run: |
           pytest --cov=app --cov-report=xml tests
      - name: Upload coverage
        uses: codecov/codecov-action@v2.0.2